name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    
    name: Python ${{ matrix.python-version }} Tests

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        python scripts/download_transducer.py --model=smor
        mkdir tmp && wget -O tmp/de_hdt-ud-dev.conllu https://raw.githubusercontent.com/UniversalDependencies/UD_German-HDT/master/de_hdt-ud-dev.conllu
    - name: Lint with flake8
      run: |
        flake8 --ignore=F401 --exclude=$(grep -v '^#' .gitignore | xargs | sed -e 's/ /,/g')
    - name: Unit Test with pytest
      run: |
        PYTHONPATH=. pytest
    #- name: Codecov
    #  uses: codecov/codecov-action@v1.4.1
